name: Code Review and Quality Checks

on: 
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  code-review:
    name: 'Perform code review using eslint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      - name: 'Install Eslint'
        run: npm init @eslint/config@latest -y

      - name: 'Scan server.js'
        run: npx eslint server.js
