name: Code Review and Quality Checks

on: 
  pull_request:
    branches:
      - main

jobs:
  code-review:
    name: 'Automate Code Review Tasks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      - name: 'Lint Code'
        run: npm run lint

      - name: 'Run Security Scans'
        run: npm run security-scan
