# using amazon ec2 instances as my local runners

name: Workflow for continuous deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy Node Application On EC2 Instance'
    runs-on: self-hosted
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2
        
      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Run Tests'
        run: npm run test

      - name: 'Restarting PM2 Process'
        run: pm2 restart nodeBackend
      



