# using amazon ec2 instances as my local runners

name: Workflow for continuous deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy the New Commits'
    runs-on: self-hosted
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run Test Cases'
        run: npm run test
