name: 'Experiment Workflow'

on: 
  pull_request:
    branches:
      - main


jobs:
  myjob:
    name: 'Print File'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: cat server.js
